# Generated by Django 4.2.6 on 2023-10-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                ("experiment_id", models.IntegerField(default=0)),
                ("cycle_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_id", models.IntegerField(default=0)),
                ("step_number", models.IntegerField(default=0)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "humidity",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                ("aa_checked", models.BooleanField(default=False)),
                ("cycle_start_time", models.DateTimeField(blank=True, null=True)),
                ("cycle_end_time", models.DateTimeField(blank=True, null=True)),
                ("time_per_cycle", models.DurationField(blank=True, null=True)),
                ("recipe", models.CharField(default="", max_length=100, null=True)),
                ("mask", models.CharField(default="", max_length=100, null=True)),
                ("amino_id", models.CharField(default="", max_length=100, null=True)),
                ("amino", models.CharField(default="", max_length=20, null=True)),
                ("notes", models.CharField(default="", max_length=300, null=True)),
            ],
        ),
    ]
